import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Card, CardContent } from "@/components/ui/card";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <footer>
              <Card className="rounded-none">
                <CardContent className="px-5 py-6">
                  <p className="text-sm text-gray-400">
                    Criado por <strong>USER_NAME</strong>
                  </p>
                </CardContent>
              </Card>
            </footer>
          </div>

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
